spring.application.name=logistica-sistema
# O Railway injeta a porta automaticamente, mas deixamos 8080 de fallback local
server.port=${PORT:8080}

# Puxa a URL segura do MongoDB do servidor, ou usa localhost se rodar na sua m quina
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/logistica_db}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB