spring.application.name=logistica-sistema
server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://carloseduardof191_db_user:WQYe3HDtVk35XON5@cluster0.uzppvwa.mongodb.net/erp_logistico?appName=Cluster0
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB