spring.application.name=logistica-sistema
server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB